apiVersion: 1
datasources:
  - name: TimescaleDB
    type: postgres
    uid: timescale
    access: proxy
    url: timescale:5432
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    isDefault: true
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 1700
      timescaledb: true
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
